CREATE TABLE IF NOT EXISTS app_security_risk_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '风险事件ID',
    user_id BIGINT UNSIGNED DEFAULT NULL COMMENT '用户ID',
    device_id VARCHAR(128) DEFAULT NULL COMMENT '设备标识',
    ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
    path VARCHAR(255) NOT NULL COMMENT '请求路径',
    method VARCHAR(16) NOT NULL COMMENT '请求方法',
    rule_code VARCHAR(80) NOT NULL COMMENT '命中规则编码',
    action VARCHAR(20) NOT NULL COMMENT '处置动作：observe/cooldown/blocked',
    risk_score INT NOT NULL DEFAULT 0 COMMENT '风险分',
    request_id VARCHAR(64) DEFAULT NULL COMMENT '请求ID',
    token_hash VARCHAR(128) DEFAULT NULL COMMENT 'token摘要',
    payload_json JSON DEFAULT NULL COMMENT '附加事件数据',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_app_security_risk_event_user_created_at (user_id, created_at),
    KEY idx_app_security_risk_event_rule_created_at (rule_code, created_at),
    KEY idx_app_security_risk_event_ip_created_at (ip, created_at),
    KEY idx_app_security_risk_event_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='反扒风险事件表';
